language: node_js
dist: trusty
addons:
  apt:
    packages:
      - ncftp

node_js:
  - node # will use latest node
before_script: # commands to run before the build step
  - npm install -g --silent @angular/cli

script: # the build step
  - npm install
  - ng build

after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then
      cd 'dist/photils';
      ncftpput -R -v -u "$USERNAME" -p "$PASSWORD" "$HOST" /development . ;
    fi

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change   